REMOVE = 'REMOVE'

MDM_22JOINT_MAP = {
    'Hips': 0, 'LeftUpLeg': 1, 'RightUpLeg': 2, 'Spine': 3, 'LeftLeg': 4, 'RightLeg': 5,
    'Spine1': 6, 'LeftFoot': 7, 'RightFoot': 8, 'Spine2': 9, 'LeftToeBase': 10, 'RightToeBase': 11,
    'Neck': 12, 'LeftShoulder': 13, 'RightShoulder': 14, 'Head': 15, 'LeftArm': 16, 'RightArm': 17,
    'LeftForeArm': 18, 'RightForeArm': 19, 'LeftHand': 20, 'RightHand': 21,
}

MDM_22JOINT_PAIRS = [
    ['Hips', 'Spine'], ['Spine', 'Spine1'], ['Spine1', 'Spine2'],
    ['Spine2', 'Neck'], ['Neck', 'Head'], ['Spine2', 'RightShoulder'],
    ['RightShoulder', 'RightArm'], ['RightArm','RightForeArm'], ['RightForeArm', 'RightHand'],
    ['Hips', 'RightUpLeg'], ['RightUpLeg', 'RightLeg'], ['RightLeg', 'RightFoot'],
    ['RightFoot', 'RightToeBase'], ['Spine2', 'LeftShoulder'], ['LeftShoulder', 'LeftArm'],
    ['LeftArm', 'LeftForeArm'], ['LeftForeArm', 'LeftHand'], ['Hips', 'LeftUpLeg'],
    ['LeftUpLeg', 'LeftLeg'], ['LeftLeg', 'LeftFoot'], ['LeftFoot', 'LeftToeBase']
]

OPENPOSE_18JOINT_MAP = {
    'Nose': 0, 'Neck': 1,
    'RShoulder': 2, 'RElbow': 3, 'RWrist': 4,
    'LShoulder': 5, 'LElbow': 6, 'LWrist': 7,
    'RHip': 8, 'RKnee': 9, 'RAnkle': 10,
    'LHip': 11, 'LKnee': 12, 'LAnkle': 13,
    'REye': 14, 'LEye': 15, 'REar': 16, 'LEar': 17
}

OPENPOSE_18JOINT_COLOR = {
    'Nose': [255, 0, 0], 'Neck': [255, 85, 0],
    'RShoulder': [255, 170, 0], 'RElbow': [255, 255, 0], 'RWrist': [170, 255, 0],
    'LShoulder': [85, 255, 0], 'LElbow': [0, 255, 0], 'LWrist': [0, 255, 85],
    'RHip': [0, 255, 170], 'RKnee': [0, 255, 255], 'RAnkle': [0, 170, 255],
    'LHip': [0, 85, 255], 'LKnee': [0, 0, 255], 'LAnkle': [85, 0, 255],
    'REye': [170, 0, 255], 'LEye': [255, 0, 255], 'REar': [255, 0, 170], 'LEar': [255, 0, 85]
}

OPENPOSE_18JOINT_PAIRS = [
    ['Neck', 'RShoulder'], ['Neck', 'LShoulder'], ['RShoulder', 'RElbow'],
    ['RElbow', 'RWrist'], ['LShoulder', 'LElbow'], ['LElbow', 'LWrist'],
    ['Neck', 'RHip'], ['RHip', 'RKnee'], ['RKnee', 'RAnkle'],
    ['Neck', 'LHip'], ['LHip', 'LKnee'], ['LKnee', 'LAnkle'],
    ['Neck', 'Nose'], ['Nose', 'REye'], ['REye', 'REar'],
    ['Nose', 'LEye'], ['LEye', 'LEar']
]

OPENPOSE_18JOINT_PAIRS_COLOR = [
    [153, 0, 0], [153, 51, 0], [153, 102, 0],
    [153, 153, 0], [102, 153, 0], [51, 153, 0],
    [0, 153, 0], [0, 153, 51], [0, 153, 102],
    [0, 153, 153], [0, 102, 153], [0, 51, 153],
    [0, 0, 153], [51, 0, 153], [102, 0, 153],
    [153, 0, 153], [153, 0, 102]
]

MDM2OPENPOSE_KEYVAL = {
    'Hips': REMOVE, 'LeftUpLeg': REMOVE, 'RightUpLeg': REMOVE, 'Spine': REMOVE,
    'LeftLeg': 'LKnee', 'RightLeg': 'RKnee', 'Spine1': REMOVE, 'LeftFoot': 'LAnkle',
    'RightFoot': 'RAnkle', 'Spine2': REMOVE, 'LeftToeBase': REMOVE, 'RightToeBase': REMOVE,
    'Neck': REMOVE, 'LeftShoulder': REMOVE, 'RightShoulder': REMOVE, 'Head': 'Nose',
    'LeftArm': 'LShoulder', 'RightArm': 'RShoulder', 'LeftForeArm': 'LElbow', 'RightForeArm': 'RElbow',
    'LeftHand': 'LWrist', 'RightHand': 'RWrist'
}

SMPLX_JOINT_NAMES = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "jaw",
    "left_eye_smplhf",
    "right_eye_smplhf",
    "left_index1",
    "left_index2",
    "left_index3",
    "left_middle1",
    "left_middle2",
    "left_middle3",
    "left_pinky1",
    "left_pinky2",
    "left_pinky3",
    "left_ring1",
    "left_ring2",
    "left_ring3",
    "left_thumb1",
    "left_thumb2",
    "left_thumb3",
    "right_index1",
    "right_index2",
    "right_index3",
    "right_middle1",
    "right_middle2",
    "right_middle3",
    "right_pinky1",
    "right_pinky2",
    "right_pinky3",
    "right_ring1",
    "right_ring2",
    "right_ring3",
    "right_thumb1",
    "right_thumb2",
    "right_thumb3",
    "nose",
    "right_eye",
    "left_eye",
    "right_ear",
    "left_ear",
    "left_big_toe",
    "left_small_toe",
    "left_heel",
    "right_big_toe",
    "right_small_toe",
    "right_heel",
    "left_thumb",
    "left_index",
    "left_middle",
    "left_ring",
    "left_pinky",
    "right_thumb",
    "right_index",
    "right_middle",
    "right_ring",
    "right_pinky",
    "right_eye_brow1",
    "right_eye_brow2",
    "right_eye_brow3",
    "right_eye_brow4",
    "right_eye_brow5",
    "left_eye_brow5",
    "left_eye_brow4",
    "left_eye_brow3",
    "left_eye_brow2",
    "left_eye_brow1",
    "nose1",
    "nose2",
    "nose3",
    "nose4",
    "right_nose_2",
    "right_nose_1",
    "nose_middle",
    "left_nose_1",
    "left_nose_2",
    "right_eye1",
    "right_eye2",
    "right_eye3",
    "right_eye4",
    "right_eye5",
    "right_eye6",
    "left_eye4",
    "left_eye3",
    "left_eye2",
    "left_eye1",
    "left_eye6",
    "left_eye5",
    "right_mouth_1",
    "right_mouth_2",
    "right_mouth_3",
    "mouth_top",
    "left_mouth_3",
    "left_mouth_2",
    "left_mouth_1",
    "left_mouth_5",  # 59 in OpenPose output
    "left_mouth_4",  # 58 in OpenPose output
    "mouth_bottom",
    "right_mouth_4",
    "right_mouth_5",
    "right_lip_1",
    "right_lip_2",
    "lip_top",
    "left_lip_2",
    "left_lip_1",
    "left_lip_3",
    "lip_bottom",
    "right_lip_3",
    # Face contour
    "right_contour_1",
    "right_contour_2",
    "right_contour_3",
    "right_contour_4",
    "right_contour_5",
    "right_contour_6",
    "right_contour_7",
    "right_contour_8",
    "contour_middle",
    "left_contour_8",
    "left_contour_7",
    "left_contour_6",
    "left_contour_5",
    "left_contour_4",
    "left_contour_3",
    "left_contour_2",
    "left_contour_1",
]